{
  "status": "INTERNAL_SERVER_ERROR",
  "technical_message": "Exception while getting user from AWS Cognito, username: errorUserId",
  "user_message": "Exception while getting user from AWS Cognito",
  "error_code": "CAP-009",
  "causes": [
    "internal error (Service: null; Status Code: 0; Error Code: null; Request ID: null)"
  ]
}